# Generated by Django 4.1.7 on 2023-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_email_about_primary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='country',
            field=models.CharField(default='Nepal', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='district',
            field=models.CharField(default='kathmandu', max_length=250),
            preserve_default=False,
        ),
    ]
