# Generated by Django 4.1.7 on 2023-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_about_country_about_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'ABOUT'},
        ),
    ]
