# Generated by Django 4.1.7 on 2023-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=100)),
                ('time', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'OPENNING HOUR',
                'unique_together': {('day', 'time')},
            },
        ),
    ]
