# Generated by Django 4.1.7 on 2023-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_about_facebook_about_instagram_about_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='openning_hour',
            field=models.CharField(default='1:00-2:00', max_length=200),
            preserve_default=False,
        ),
    ]
