# Generated by Django 4.1.7 on 2023-03-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_about_openning_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default='this is the description about bawarchi'),
            preserve_default=False,
        ),
    ]
