# Generated by Django 4.1.7 on 2023-03-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='staff')),
                ('position', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'STAFF',
            },
        ),
    ]
