# Generated by Django 4.1.7 on 2023-03-07 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'TESTIMONIALS'},
        ),
        migrations.AddField(
            model_name='testimonials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
