# Generated by Django 4.1.7 on 2023-03-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_testimonials_options_testimonials_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
