# Generated by Django 4.1.7 on 2023-03-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_item_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
