# Generated by Django 4.1.7 on 2023-03-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_order_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(),
        ),
    ]
