# Generated by Django 4.1.7 on 2023-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_img_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boolsd',
            field=models.BooleanField(default=True),
        ),
    ]
