# Generated by Django 4.1.7 on 2023-02-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_boolsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boolsd',
        ),
    ]
